name: Cucumber Daily Test

on:
  schedule:
    # At 0AM UTC of every day
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run cucumber test
      run: ./gradlew cucumber
